# Generated by Django 4.2.5 on 2023-10-25 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
