# Generated by Django 4.2.2 on 2023-09-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('heading', models.CharField(max_length=255)),
                ('sub_heading', models.TextField()),
            ],
            options={
                'verbose_name': 'نص الصفحة الرئيسية',
                'verbose_name_plural': 'الصفحة الرئيسية',
            },
        ),
    ]
