# Generated by Django 4.2.5 on 2023-09-28 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='السعر (ريال سعودي)')),
                ('space', models.IntegerField(default=0, verbose_name='المساحة (متر مربع)')),
                ('width', models.FloatField(verbose_name='العرض (متر)')),
                ('length', models.FloatField(verbose_name='الطول (متر)')),
                ('advertiser_relation', models.CharField(max_length=50, verbose_name='علاقة المعلن بالعقار')),
                ('exclusive', models.BooleanField(default=False, verbose_name='حصري')),
                ('video', models.FileField(upload_to='rent/apartment/video', verbose_name='فيديو')),
                ('street_width', models.FloatField(verbose_name='عرض الشارع')),
                ('rooms', models.IntegerField(default=0)),
                ('lounges', models.IntegerField(default=0, verbose_name='الصالات')),
                ('bathroom', models.IntegerField(default=0, verbose_name='عدد دورات المياه')),
                ('floor', models.IntegerField(default=0, verbose_name='الدور')),
                ('property_age', models.IntegerField(default=0, verbose_name='عمر العقار')),
                ('families', models.BooleanField(default=True, verbose_name='عوائل ام عزاب')),
                ('rent_type', models.CharField(choices=[('yearly', 'سنوي'), ('monthly', 'شهري')], max_length=50, verbose_name='نوع الإيجار')),
                ('description', models.TextField(verbose_name='وصف العقار')),
                ('furnished', models.BooleanField(default=False, verbose_name='مؤثثة')),
                ('kitchen', models.BooleanField(default=False, verbose_name='مطبخ')),
                ('extenstion', models.BooleanField(default=False, verbose_name='ملحق')),
                ('car_entrance', models.BooleanField(default=False, verbose_name='مدخل سيارة')),
                ('elevator', models.BooleanField(default=False, verbose_name='مصعد كهربائي')),
                ('ac', models.BooleanField(default=False, verbose_name='مكيف')),
                ('water_exist', models.BooleanField(default=False, verbose_name='توفر الماء')),
                ('power_exist', models.BooleanField(default=False, verbose_name='توفر الكهرباء')),
                ('sanitation_exist', models.BooleanField(default=False, verbose_name='توفر الصرف')),
                ('private_surface', models.BooleanField(default=False, verbose_name='سطح خاص')),
                ('in_villa', models.BooleanField(default=False, verbose_name='في فيلا')),
                ('two_enternace', models.BooleanField(default=False, verbose_name='مدخلين')),
                ('private_enternace', models.BooleanField(default=False, verbose_name='مدخل خاص')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'BuildingRent',
                'verbose_name_plural': 'BuildingRents',
            },
        ),
        migrations.CreateModel(
            name='ChaletRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ChaletRent',
                'verbose_name_plural': 'ChaletRents',
            },
        ),
        migrations.CreateModel(
            name='CommercialOfficeRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'CommercialOfficeRent',
                'verbose_name_plural': 'CommercialOfficeRents',
            },
        ),
        migrations.CreateModel(
            name='FloorRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='السعر (ريال سعودي)')),
                ('space', models.IntegerField(default=0, verbose_name='المساحة (متر مربع)')),
                ('width', models.FloatField(verbose_name='العرض (متر)')),
                ('length', models.FloatField(verbose_name='الطول (متر)')),
                ('advertiser_relation', models.CharField(max_length=50, verbose_name='علاقة المعلن بالعقار')),
                ('exclusive', models.BooleanField(default=False, verbose_name='حصري')),
                ('video', models.FileField(upload_to='rent/floor/video', verbose_name='فيديو')),
                ('street_width', models.FloatField(verbose_name='عرض الشارع')),
                ('rooms', models.IntegerField(default=0)),
                ('lounges', models.IntegerField(default=0, verbose_name='الصالات')),
                ('bathroom', models.IntegerField(default=0, verbose_name='عدد دورات المياه')),
                ('floor', models.IntegerField(default=0, verbose_name='الدور')),
                ('property_age', models.IntegerField(default=0, verbose_name='عمر العقار')),
                ('families', models.BooleanField(default=True, verbose_name='عوائل ام عزاب')),
                ('rent_type', models.CharField(choices=[('yearly', 'سنوي'), ('monthly', 'شهري')], max_length=50, verbose_name='نوع الإيجار')),
                ('description', models.TextField(verbose_name='وصف العقار')),
                ('furnished', models.BooleanField(default=False, verbose_name='مؤثثة')),
                ('kitchen', models.BooleanField(default=False, verbose_name='مطبخ')),
                ('extenstion', models.BooleanField(default=False, verbose_name='ملحق')),
                ('car_entrance', models.BooleanField(default=False, verbose_name='مدخل سيارة')),
                ('elevator', models.BooleanField(default=False, verbose_name='مصعد كهربائي')),
                ('ac', models.BooleanField(default=False, verbose_name='مكيف')),
                ('water_exist', models.BooleanField(default=False, verbose_name='توفر الماء')),
                ('power_exist', models.BooleanField(default=False, verbose_name='توفر الكهرباء')),
                ('sanitation_exist', models.BooleanField(default=False, verbose_name='توفر الصرف')),
                ('private_surface', models.BooleanField(default=False, verbose_name='سطح خاص')),
                ('in_villa', models.BooleanField(default=False, verbose_name='في فيلا')),
                ('two_enternace', models.BooleanField(default=False, verbose_name='مدخلين')),
                ('private_enternace', models.BooleanField(default=False, verbose_name='مدخل خاص')),
            ],
            options={
                'verbose_name': 'FloorRent',
                'verbose_name_plural': 'FloorRents',
            },
        ),
        migrations.CreateModel(
            name='FurnishedApartmentRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LandRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'LandRent',
                'verbose_name_plural': 'LandRents',
            },
        ),
        migrations.CreateModel(
            name='RestHouseRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'RestHouseRent',
                'verbose_name_plural': 'RestHouseRents',
            },
        ),
        migrations.CreateModel(
            name='ShopRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ShopRent',
                'verbose_name_plural': 'ShopRents',
            },
        ),
        migrations.CreateModel(
            name='VillaRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=100, verbose_name='الواجهة')),
                ('price', models.IntegerField(default=0, verbose_name='السعر (ريال سعودي)')),
                ('space', models.IntegerField(default=0, verbose_name='المساحة (متر مربع)')),
                ('width', models.FloatField(verbose_name='العرض (متر)')),
                ('length', models.FloatField(verbose_name='الطول (متر)')),
                ('advertiser_relation', models.CharField(max_length=50, verbose_name='علاقة المعلن بالعقار')),
                ('exclusive', models.BooleanField(default=False, verbose_name='حصري')),
                ('video', models.FileField(upload_to='rent/villa/video', verbose_name='فيديو')),
                ('street_width', models.FloatField(verbose_name='عرض الشارع')),
                ('rooms', models.IntegerField(default=0)),
                ('lounges', models.IntegerField(default=0, verbose_name='الصالات')),
                ('bathroom', models.IntegerField(default=0, verbose_name='عدد دورات المياه')),
                ('floor', models.IntegerField(default=0, verbose_name='الدور')),
                ('property_age', models.IntegerField(default=0, verbose_name='عمر العقار')),
                ('families', models.BooleanField(default=True, verbose_name='عوائل ام عزاب')),
                ('rent_type', models.CharField(choices=[('yearly', 'سنوي'), ('monthly', 'شهري')], max_length=50, verbose_name='نوع الإيجار')),
                ('description', models.TextField(verbose_name='وصف العقار')),
                ('furnished', models.BooleanField(default=False, verbose_name='مؤثثة')),
                ('kitchen', models.BooleanField(default=False, verbose_name='مطبخ')),
                ('extenstion', models.BooleanField(default=False, verbose_name='ملحق')),
                ('car_entrance', models.BooleanField(default=False, verbose_name='مدخل سيارة')),
                ('elevator', models.BooleanField(default=False, verbose_name='مصعد كهربائي')),
                ('ac', models.BooleanField(default=False, verbose_name='مكيف')),
                ('water_exist', models.BooleanField(default=False, verbose_name='توفر الماء')),
                ('power_exist', models.BooleanField(default=False, verbose_name='توفر الكهرباء')),
                ('sanitation_exist', models.BooleanField(default=False, verbose_name='توفر الصرف')),
                ('private_surface', models.BooleanField(default=False, verbose_name='سطح خاص')),
                ('in_villa', models.BooleanField(default=False, verbose_name='في فيلا')),
                ('two_enternace', models.BooleanField(default=False, verbose_name='مدخلين')),
                ('private_enternace', models.BooleanField(default=False, verbose_name='مدخل خاص')),
                ('driver_room', models.BooleanField(default=False, verbose_name='غرفة سائق')),
                ('maid_room', models.BooleanField(default=False, verbose_name='غرفة خادمة')),
                ('duplex', models.BooleanField(default=False, verbose_name='دوبلكس')),
                ('view', models.BooleanField(default=False, verbose_name='فيو')),
                ('yard', models.BooleanField(default=False, verbose_name='حوش')),
                ('hair_tent_house', models.BooleanField(default=False, verbose_name='بيت شعر')),
            ],
            options={
                'verbose_name': 'VillaRent',
                'verbose_name_plural': 'VillaRents',
            },
        ),
        migrations.CreateModel(
            name='WarehouseRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VillaRentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='rent/villa/')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.villarent', verbose_name='الإعلان')),
            ],
        ),
        migrations.CreateModel(
            name='FloorRentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='rent/floor/')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.floorrent', verbose_name='الإعلان')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentRentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='rent/apartment/')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.apartmentrent', verbose_name='الإعلان')),
            ],
        ),
    ]
