# Generated by Django 4.2.5 on 2023-10-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentrent',
            name='floor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='الدور'),
        ),
    ]
