# Generated by Django 4.2.5 on 2023-10-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_apartmentrent_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentrent',
            name='description',
            field=models.TextField(blank=True, default='   ', null=True, verbose_name='وصف العقار'),
        ),
    ]
