# Generated by Django 4.2.5 on 2023-09-28 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_shoprent_description_shoprent_interface_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialofficerent',
            name='bathroom',
            field=models.IntegerField(default=0, verbose_name='عدد دورات المياه'),
        ),
        migrations.AddField(
            model_name='commercialofficerent',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف العقار'),
        ),
        migrations.AddField(
            model_name='commercialofficerent',
            name='floor',
            field=models.IntegerField(default=False, verbose_name='الدور'),
        ),
        migrations.AddField(
            model_name='commercialofficerent',
            name='furnished',
            field=models.BooleanField(default=False, verbose_name='مؤثثة'),
        ),
        migrations.AddField(
            model_name='commercialofficerent',
            name='lounges',
            field=models.IntegerField(default=0, verbose_name='الصالات'),
        ),
        migrations.AddField(
            model_name='commercialofficerent',
            name='power_exist',
            field=models.BooleanField(default=False, verbose_name='توفر الكهرباء'),
        ),
        migrations.AddField(
            model_name='commercialofficerent',
            name='property_age',
            field=models.IntegerField(default=0, verbose_name='عمر العقار'),
        ),
        migrations.AddField(
            model_name='commercialofficerent',
            name='rooms',
            field=models.IntegerField(default=0, verbose_name='الغرف'),
        ),
        migrations.AddField(
            model_name='commercialofficerent',
            name='sanitation_exist',
            field=models.BooleanField(default=False, verbose_name='توفر الصرف'),
        ),
        migrations.AddField(
            model_name='commercialofficerent',
            name='street_width',
            field=models.IntegerField(default=0, verbose_name='عرض الشارع'),
        ),
        migrations.AddField(
            model_name='commercialofficerent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='rent/commercial_office/video', verbose_name='فيديو'),
        ),
        migrations.AddField(
            model_name='commercialofficerent',
            name='water_exist',
            field=models.BooleanField(default=False, verbose_name='توفر الماء'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='amusement',
            field=models.BooleanField(default=False, verbose_name='ملاهي'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='bathroom',
            field=models.IntegerField(default=0, verbose_name='عدد دورات المياه'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف العقار'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='family_part',
            field=models.BooleanField(default=False, verbose_name='قسم عوائل'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='football_field',
            field=models.BooleanField(default=False, verbose_name='ملعب كرة قدم'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='hair_tent_house',
            field=models.BooleanField(default=False, verbose_name='بيت شعر'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='kitchen',
            field=models.BooleanField(default=False, verbose_name='مطبخ'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='lounges',
            field=models.IntegerField(default=0, verbose_name='الصالات'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='pool',
            field=models.BooleanField(default=False, verbose_name='مسبح'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='power_exist',
            field=models.BooleanField(default=False, verbose_name='توفر الكهرباء'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='property_age',
            field=models.IntegerField(default=0, verbose_name='عمر العقار'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='rooms',
            field=models.IntegerField(default=0, verbose_name='الغرف'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='sanitation_exist',
            field=models.BooleanField(default=False, verbose_name='توفر الصرف'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='street_width',
            field=models.IntegerField(default=0, verbose_name='عرض الشارع'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='rent/rest_house/video', verbose_name='فيديو'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='volly_field',
            field=models.BooleanField(default=False, verbose_name='ملعب كرة طائرة'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='water_exist',
            field=models.BooleanField(default=False, verbose_name='توفر الماء'),
        ),
        migrations.AddField(
            model_name='shoprent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='rent/shop_rent/', verbose_name='فيديو'),
        ),
        migrations.AlterField(
            model_name='apartmentrent',
            name='rooms',
            field=models.IntegerField(default=0, verbose_name='الغرف'),
        ),
        migrations.CreateModel(
            name='ShopRentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='rent/shop_rent/')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.shoprent', verbose_name='الإعلان')),
            ],
        ),
        migrations.CreateModel(
            name='RestHouseRentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='rent/rest_house/')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.resthouserent', verbose_name='الإعلان')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialOfficeRentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='rent/commercial_office/')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.resthouserent', verbose_name='الإعلان')),
            ],
        ),
    ]
