# Generated by Django 4.2.5 on 2023-10-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_apartmentrent_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentrent',
            name='rent_type',
            field=models.CharField(blank=True, choices=[('yearly', 'سنوي'), ('monthly', 'شهري')], max_length=50, null=True, verbose_name='نوع الإيجار'),
        ),
    ]
