# Generated by Django 4.2.5 on 2023-09-28 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_commercialofficerent_bathroom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
            ],
        ),
        migrations.RemoveField(
            model_name='villarent',
            name='view',
        ),
        migrations.AddField(
            model_name='buildingrent',
            name='apartments_count',
            field=models.IntegerField(default=0, verbose_name='عدد الشقق'),
        ),
        migrations.AddField(
            model_name='buildingrent',
            name='basement',
            field=models.BooleanField(default=False, verbose_name='قبو'),
        ),
        migrations.AddField(
            model_name='buildingrent',
            name='description',
            field=models.TextField(default='   ', verbose_name='وصف العقار'),
        ),
        migrations.AddField(
            model_name='buildingrent',
            name='furnished',
            field=models.BooleanField(default=False, verbose_name='مؤثثة'),
        ),
        migrations.AddField(
            model_name='buildingrent',
            name='interface',
            field=models.CharField(blank=True, choices=[('شمالية', 'شمالية'), ('جنوبية', 'جنوبية'), ('غربية', 'غربية'), ('شرقية', 'شرقية'), ('شمالية شرقية', 'شمالية شرقية'), ('شمالية غربية', 'شمالية غربية'), ('جنوبية شرقية', 'جنوبية شرقية'), ('جنوبية غربية', 'جنوبية غربية')], max_length=100, null=True, verbose_name='الواجهة'),
        ),
        migrations.AddField(
            model_name='buildingrent',
            name='power_exist',
            field=models.BooleanField(default=False, verbose_name='توفر الكهرباء'),
        ),
        migrations.AddField(
            model_name='buildingrent',
            name='property_age',
            field=models.IntegerField(default=0, verbose_name='عمر العقار'),
        ),
        migrations.AddField(
            model_name='buildingrent',
            name='rooms',
            field=models.IntegerField(default=0, verbose_name='الغرف'),
        ),
        migrations.AddField(
            model_name='buildingrent',
            name='sanitation_exist',
            field=models.BooleanField(default=False, verbose_name='توفر الصرف'),
        ),
        migrations.AddField(
            model_name='buildingrent',
            name='sotres_count',
            field=models.IntegerField(default=0, verbose_name='عدد المحلات'),
        ),
        migrations.AddField(
            model_name='buildingrent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='rent/land/video', verbose_name='فيديو'),
        ),
        migrations.AddField(
            model_name='buildingrent',
            name='water_exist',
            field=models.BooleanField(default=False, verbose_name='توفر الماء'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='description',
            field=models.TextField(default='  ', verbose_name='وصف العقار'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='interface',
            field=models.CharField(blank=True, choices=[('شمالية', 'شمالية'), ('جنوبية', 'جنوبية'), ('غربية', 'غربية'), ('شرقية', 'شرقية'), ('شمالية شرقية', 'شمالية شرقية'), ('شمالية غربية', 'شمالية غربية'), ('جنوبية شرقية', 'جنوبية شرقية'), ('جنوبية غربية', 'جنوبية غربية')], max_length=100, null=True, verbose_name='الواجهة'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='power_exist',
            field=models.BooleanField(default=False, verbose_name='توفر الكهرباء'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='sanitation_exist',
            field=models.BooleanField(default=False, verbose_name='توفر الصرف'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='street_width',
            field=models.FloatField(blank=True, null=True, verbose_name='عرض الشارع'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='rent/land/video', verbose_name='فيديو'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='water_exist',
            field=models.BooleanField(default=False, verbose_name='توفر الماء'),
        ),
        migrations.AddField(
            model_name='villarent',
            name='basement',
            field=models.BooleanField(default=False, verbose_name='قبو'),
        ),
        migrations.AlterField(
            model_name='apartmentrent',
            name='description',
            field=models.TextField(default='   ', verbose_name='وصف العقار'),
        ),
        migrations.CreateModel(
            name='LandRentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='rent/land/')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.resthouserent', verbose_name='الإعلان')),
            ],
        ),
        migrations.AddField(
            model_name='buildingrent',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.purpose'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.purpose'),
        ),
    ]
