# Generated by Django 4.2.5 on 2023-09-28 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_purpose_remove_villarent_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingrent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='rent/building/video', verbose_name='فيديو'),
        ),
        migrations.CreateModel(
            name='BuildingRentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='rent/building/')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.resthouserent', verbose_name='الإعلان')),
            ],
        ),
    ]
