# Generated by Django 4.2.5 on 2023-09-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_buildingrent_video_buildingrentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouserent',
            name='description',
            field=models.TextField(default='   ', verbose_name='وصف العقار'),
        ),
        migrations.AddField(
            model_name='warehouserent',
            name='interface',
            field=models.CharField(blank=True, choices=[('شمالية', 'شمالية'), ('جنوبية', 'جنوبية'), ('غربية', 'غربية'), ('شرقية', 'شرقية'), ('شمالية شرقية', 'شمالية شرقية'), ('شمالية غربية', 'شمالية غربية'), ('جنوبية شرقية', 'جنوبية شرقية'), ('جنوبية غربية', 'جنوبية غربية')], max_length=100, null=True, verbose_name='الواجهة'),
        ),
        migrations.AddField(
            model_name='warehouserent',
            name='power_exist',
            field=models.BooleanField(default=False, verbose_name='توفر الكهرباء'),
        ),
        migrations.AddField(
            model_name='warehouserent',
            name='property_age',
            field=models.IntegerField(default=0, verbose_name='عمر العقار'),
        ),
        migrations.AddField(
            model_name='warehouserent',
            name='sanitation_exist',
            field=models.BooleanField(default=False, verbose_name='توفر الصرف'),
        ),
        migrations.AddField(
            model_name='warehouserent',
            name='street_width',
            field=models.FloatField(blank=True, null=True, verbose_name='عرض الشارع'),
        ),
        migrations.AddField(
            model_name='warehouserent',
            name='water_exist',
            field=models.BooleanField(default=False, verbose_name='توفر الماء'),
        ),
    ]
