# Generated by Django 4.2.5 on 2023-10-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_remove_apartmentrent_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentrent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='rent/apartment/video', verbose_name='فيديو'),
        ),
    ]
