# Generated by Django 4.2.5 on 2023-10-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_apartmentrent_street_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentrent',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='apartmentrent',
            name='lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
