# Generated by Django 4.2.5 on 2023-10-03 09:08

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_chaletrent_amusement_chaletrent_bathroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentrent',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True),
        ),
    ]
