# Generated by Django 4.2.5 on 2023-10-03 09:10

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_apartmentrent_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentrent',
            name='position',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
    ]
