# Generated by Django 4.2.5 on 2023-10-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_apartmentrent_lat_apartmentrent_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentrent',
            name='property_age',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عمر العقار'),
        ),
    ]
