# Generated by Django 4.2.5 on 2023-10-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_apartmentrent_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentrent',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان الإعلان'),
        ),
    ]
