# Generated by Django 4.2.5 on 2023-10-04 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_apartmentrent_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentrentimage',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='property.apartmentrent', verbose_name='الإعلان'),
        ),
    ]
