# Generated by Django 4.2.5 on 2023-10-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_alter_apartmentrentimage_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentrent',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الإعلان'),
        ),
    ]
