# Generated by Django 4.2.5 on 2023-10-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_alter_apartmentrent_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentrent',
            name='lounges',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='الصالات'),
        ),
    ]
