# Generated by Django 4.2.5 on 2023-10-06 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_apartmentrent_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingrent',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الإعلان'),
        ),
        migrations.AddField(
            model_name='chaletrent',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الإعلان'),
        ),
        migrations.AddField(
            model_name='chaletrent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='rent/chalet/video', verbose_name='فيديو'),
        ),
        migrations.AddField(
            model_name='commercialofficerent',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الإعلان'),
        ),
        migrations.AddField(
            model_name='floorrent',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الإعلان'),
        ),
        migrations.AddField(
            model_name='furnishedapartmentrent',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الإعلان'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الإعلان'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الإعلان'),
        ),
        migrations.AddField(
            model_name='shoprent',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الإعلان'),
        ),
        migrations.AddField(
            model_name='villarent',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الإعلان'),
        ),
        migrations.AddField(
            model_name='warehouserent',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الإعلان'),
        ),
        migrations.CreateModel(
            name='FurnishedApartmentRentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='rent/furnished-apartment/')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.furnishedapartmentrent', verbose_name='الإعلان')),
            ],
        ),
        migrations.CreateModel(
            name='ChaletRentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='rent/chalet/')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.chaletrent', verbose_name='الإعلان')),
            ],
        ),
    ]
