# Generated by Django 4.2.5 on 2023-10-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_floorrent_lat_floorrent_lng_alter_floorrent_bathroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorrent',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='الطول (متر)'),
        ),
        migrations.AlterField(
            model_name='floorrent',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='العرض (متر)'),
        ),
    ]
