# Generated by Django 4.2.5 on 2023-10-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_floorrent_length_alter_floorrent_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villarent',
            name='bathroom',
            field=models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='عدد دورات المياه'),
        ),
        migrations.AlterField(
            model_name='villarent',
            name='floor',
            field=models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='الدور'),
        ),
        migrations.AlterField(
            model_name='villarent',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='الطول (متر)'),
        ),
        migrations.AlterField(
            model_name='villarent',
            name='lounges',
            field=models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='الصالات'),
        ),
        migrations.AlterField(
            model_name='villarent',
            name='property_age',
            field=models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='عمر العقار'),
        ),
        migrations.AlterField(
            model_name='villarent',
            name='rooms',
            field=models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='عدد الغرف'),
        ),
        migrations.AlterField(
            model_name='villarent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='rent/villa/video', verbose_name='فيديو'),
        ),
        migrations.AlterField(
            model_name='villarent',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='العرض (متر)'),
        ),
    ]
