# Generated by Django 4.2.5 on 2023-10-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_alter_villarent_bathroom_alter_villarent_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='villarent',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='villarent',
            name='lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
