# Generated by Django 4.2.5 on 2023-10-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_villarent_lat_villarent_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoprent',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='السعر'),
        ),
    ]
