# Generated by Django 4.2.5 on 2023-10-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_shoprent_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoprent',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoprent',
            name='lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoprent',
            name='space',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='المساحة'),
        ),
    ]
