# Generated by Django 4.2.5 on 2023-10-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_shoprent_lat_shoprent_lng_shoprent_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoprent',
            name='advertiser_relation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='علاقة المعلن بالعقار'),
        ),
        migrations.AddField(
            model_name='shoprent',
            name='exclusive',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='حصري'),
        ),
    ]
