# Generated by Django 4.2.5 on 2023-10-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_shoprent_advertiser_relation_shoprent_exclusive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resthouserent',
            name='bathroom',
            field=models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='عدد دورات المياه'),
        ),
        migrations.AlterField(
            model_name='resthouserent',
            name='lounges',
            field=models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='الصالات'),
        ),
        migrations.AlterField(
            model_name='resthouserent',
            name='rooms',
            field=models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='الغرف'),
        ),
    ]
