# Generated by Django 4.2.5 on 2023-10-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_alter_resthouserent_bathroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resthouserent',
            name='rent_type',
            field=models.CharField(blank=True, choices=[('yearly', 'سنوي'), ('monthly', 'شهري')], max_length=50, null=True, verbose_name='نوع الإيجار'),
        ),
        migrations.AddField(
            model_name='shoprent',
            name='rent_type',
            field=models.CharField(blank=True, choices=[('yearly', 'سنوي'), ('monthly', 'شهري')], max_length=50, null=True, verbose_name='نوع الإيجار'),
        ),
    ]
