# Generated by Django 4.2.5 on 2023-10-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_resthouserent_rent_type_shoprent_rent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resthouserent',
            name='advertiser_relation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='علاقة المعلن بالعقار'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='exclusive',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='حصري'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='price',
            field=models.IntegerField(default=0, verbose_name='السعر (ريال سعودي)'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='space',
            field=models.IntegerField(default=0, verbose_name='المساحة (متر مربع)'),
        ),
    ]
