# Generated by Django 4.2.5 on 2023-10-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_resthouserent_advertiser_relation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resthouserent',
            name='property_age',
            field=models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='عمر العقار'),
        ),
    ]
