# Generated by Django 4.2.5 on 2023-10-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_alter_resthouserent_property_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landrent',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الغرض'),
        ),
    ]
