# Generated by Django 4.2.5 on 2023-10-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_alter_landrent_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingrent',
            name='apartments_count',
            field=models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='عدد الشقق'),
        ),
        migrations.AlterField(
            model_name='buildingrent',
            name='property_age',
            field=models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='عمر العقار'),
        ),
        migrations.AlterField(
            model_name='buildingrent',
            name='purpose',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الغرض'),
        ),
        migrations.AlterField(
            model_name='buildingrent',
            name='sotres_count',
            field=models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='عدد المحلات'),
        ),
    ]
