# Generated by Django 4.2.5 on 2023-10-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_buildingrent_lat_buildingrent_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingrent',
            name='advertiser_relation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='علاقة المعلن بالعقار'),
        ),
        migrations.AddField(
            model_name='buildingrent',
            name='exclusive',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='حصري'),
        ),
        migrations.AddField(
            model_name='buildingrent',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='السعر (ريال سعودي)'),
        ),
        migrations.AddField(
            model_name='buildingrent',
            name='rooms',
            field=models.CharField(blank=True, default=0, max_length=10, null=True, verbose_name='الغرف'),
        ),
        migrations.AddField(
            model_name='buildingrent',
            name='space',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='المساحة (متر مربع)'),
        ),
        migrations.AddField(
            model_name='buildingrent',
            name='street_width',
            field=models.FloatField(blank=True, null=True, verbose_name='عرض الشارع'),
        ),
    ]
