# Generated by Django 4.2.5 on 2023-10-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0030_commercialofficerent_lat_commercialofficerent_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentrent',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='apartmentrent',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='الحي'),
        ),
        migrations.AddField(
            model_name='apartmentrent',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الإعلان'),
        ),
    ]
