# Generated by Django 4.2.5 on 2023-10-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0032_apartmentrentimage_main_buildingrentimage_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingrent',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='buildingrent',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='الحي'),
        ),
        migrations.AddField(
            model_name='buildingrent',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الإعلان'),
        ),
        migrations.AddField(
            model_name='chaletrent',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='chaletrent',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chaletrent',
            name='lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chaletrent',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='الحي'),
        ),
        migrations.AddField(
            model_name='chaletrent',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الإعلان'),
        ),
        migrations.AddField(
            model_name='commercialofficerent',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='commercialofficerent',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='الحي'),
        ),
        migrations.AddField(
            model_name='commercialofficerent',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الإعلان'),
        ),
        migrations.AddField(
            model_name='floorrent',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='floorrent',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='الحي'),
        ),
        migrations.AddField(
            model_name='floorrent',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الإعلان'),
        ),
        migrations.AddField(
            model_name='furnishedapartmentrent',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='furnishedapartmentrent',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='furnishedapartmentrent',
            name='lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='furnishedapartmentrent',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='الحي'),
        ),
        migrations.AddField(
            model_name='furnishedapartmentrent',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الإعلان'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landrent',
            name='lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='landrent',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='الحي'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الإعلان'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='الحي'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الإعلان'),
        ),
        migrations.AddField(
            model_name='shoprent',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='shoprent',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='الحي'),
        ),
        migrations.AddField(
            model_name='shoprent',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الإعلان'),
        ),
        migrations.AddField(
            model_name='villarent',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='villarent',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='الحي'),
        ),
        migrations.AddField(
            model_name='villarent',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الإعلان'),
        ),
        migrations.AddField(
            model_name='warehouserent',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='warehouserent',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='warehouserent',
            name='lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='warehouserent',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='الحي'),
        ),
        migrations.AddField(
            model_name='warehouserent',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الإعلان'),
        ),
    ]
