# Generated by Django 4.2.5 on 2023-10-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0033_buildingrent_city_buildingrent_neighborhood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentrent',
            name='sale',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='للبيع'),
        ),
        migrations.AddField(
            model_name='buildingrent',
            name='sale',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='للبيع'),
        ),
        migrations.AddField(
            model_name='chaletrent',
            name='sale',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='للبيع'),
        ),
        migrations.AddField(
            model_name='commercialofficerent',
            name='sale',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='للبيع'),
        ),
        migrations.AddField(
            model_name='floorrent',
            name='sale',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='للبيع'),
        ),
        migrations.AddField(
            model_name='furnishedapartmentrent',
            name='sale',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='للبيع'),
        ),
        migrations.AddField(
            model_name='landrent',
            name='sale',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='للبيع'),
        ),
        migrations.AddField(
            model_name='resthouserent',
            name='sale',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='للبيع'),
        ),
        migrations.AddField(
            model_name='shoprent',
            name='sale',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='للبيع'),
        ),
        migrations.AddField(
            model_name='villarent',
            name='sale',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='للبيع'),
        ),
        migrations.AddField(
            model_name='warehouserent',
            name='sale',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='للبيع'),
        ),
    ]
